const actionsEnum = {
    GET_ALL_CONTACTS: 'GET_ALL_CONTACTS',
    GET_CONTACT: 'GET_CONTACT',
    NEW_CONTACT: 'CREATE_CONTACT',
    EDIT_CONTACT: 'EDIT_CONTACT',

    UPDATE_CONTACT : 'UPDATE_CONTACT',
    SAVE_CONTACT : 'SAVE_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT'
};

export default actionsEnum;